plugins {
    id 'com.android.application'
}

android {
    namespace 'com.google.android.youtube'
    compileSdk 35

    defaultConfig {
        applicationId 'com.google.android.youtube'
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }
}
